version: '3.8'

services:

  mysql-db:
    image: mysql:8.0
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: WJ@28@krhps
      MYSQL_DATABASE: billingSystemDb
      MYSQL_USER: root
      MYSQL_PASSWORD:  WJ@28@krhps
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
